name: invasive
dependencies:
- alabaster=0.7.7=py35_0
- babel=2.2.0=py35_0
- basemap=1.0.7=np110py35_0
- cffi=1.5.2=py35_0
- cryptography=1.0.2=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- docutils=0.12=py35_0
- et_xmlfile=1.0.1=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- geos=3.3.3=0
- idna=2.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jdcal=1.2=py35_0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.2.1=py35_0
- jupyter_core=4.1.0=py35_0
- libffi=3.0.13=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.4=py35_1
- openssl=1.0.2g=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pep8=1.7.0=py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_0
- psutil=4.0.0=py35_0
- ptyprocess=0.5=py35_0
- pyasn1=0.1.9=py35_0
- pycparser=2.14=py35_0
- pyflakes=1.1.0=py35_0
- pygments=2.1.1=py35_0
- pyopenssl=0.15.1=py35_1
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.5.1=py35_0
- pytz=2016.2=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- rope=0.9.4=py35_1
- setuptools=20.3=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- spyder=2.3.8=py35_1
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xlrd=0.9.4=py35_0
- xz=5.0.5=1
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - et-xmlfile==1.0.1
  - folium==0.2.0
  - gbif==0.1.0
  - google-api-python-client==1.5.0
  - gspread==0.3.0
  - http-parser==0.8.3
  - httplib2==0.9.2
  - ipython-genutils==0.1.0
  - ipywidgets==4.1.1
  - jupyter==1.0.0
  - jupyter-client==4.2.1
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - oauth2client==2.0.1
  - pyasn1-modules==0.0.8
  - python-contrib-nbextensions==alpha
  - pyyaml==3.11
  - requests==2.9.1
  - restkit==4.2.2
  - rope-py3k==0.9.4.post1
  - rsa==3.3
  - simplejson==3.8.2
  - socketpool==0.5.3
  - sphinx-rtd-theme==0.1.9
  - uritemplate==0.6
  - webapp2==2.5.2

